# Generated by Django 2.1.7 on 2019-02-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('modificada', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=256)),
                ('horas_asignadas', models.FloatField()),
                ('horas_disponibles', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('tipo', models.CharField(choices=[('Req', 'Requerimiento'), ('Err', 'Error'), ('Tar', 'Tarea'), ('Sub', 'Subtarea'), ('Epi', 'Epic')], max_length=3)),
                ('codigo', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('horas_estimadas', models.FloatField()),
                ('horas_trabajadas', models.FloatField()),
                ('reasignada', models.BooleanField(default=False)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('cartel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Cartel')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=512)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Pagada'), ('8', 'Por pagar')], max_length=2)),
                ('incidencia', models.ManyToManyField(to='tracking.Incidencia')),
                ('sprint', models.ManyToManyField(to='tracking.Cartel')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('rol', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sprint_fin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint_fin', to='tracking.Sprint'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sprint_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint_inicio', to='tracking.Sprint'),
        ),
        migrations.AddField(
            model_name='asignado',
            name='incidencia',
            field=models.ManyToManyField(to='tracking.Incidencia'),
        ),
        migrations.AddField(
            model_name='asignado',
            name='responsable',
            field=models.ManyToManyField(to='tracking.Responsable'),
        ),
    ]
