# Generated by Django 2.1.7 on 2019-06-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('1', 'Sin pagar'), ('2', 'Por pagar'), ('3', 'Pagada'), ('4', 'Desarrollo CI'), ('5', 'Garantía')], max_length=3)),
                ('facturacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=1024)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=1024)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Externa por horas'), ('2', 'Externa por productos'), ('3', 'Interna CI')], max_length=3)),
                ('rol', models.CharField(choices=[('1', 'Desarrollador(a)'), ('2', 'Analista'), ('3', 'Consultor(a)')], max_length=3)),
                ('contrato', models.CharField(blank=True, max_length=1024, null=True)),
                ('orden_compra', models.CharField(blank=True, max_length=128, null=True)),
                ('horas_contratadas', models.FloatField(null=True)),
                ('horas_consumidas', models.FloatField(default=0)),
                ('presupuesto_adjudicado', models.FloatField(null=True)),
                ('presupuesto_consumido', models.FloatField(null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido1', models.CharField(max_length=32)),
                ('apellido2', models.CharField(max_length=32)),
                ('identificacion', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_facturadas', models.FloatField(default=0, null=True)),
                ('monto_facturado', models.FloatField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Contratacion')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Pagada'), ('8', 'Por pagar')], max_length=2)),
                ('tipo', models.CharField(choices=[('Req', 'Requerimiento'), ('Err', 'Error'), ('Tar', 'Tarea'), ('Sub', 'Subtarea'), ('Epi', 'Epic')], max_length=3)),
                ('horas_estimadas', models.FloatField(default=0)),
                ('horas_trabajadas', models.FloatField(default=0)),
                ('horas_por_pagar', models.FloatField(default=0)),
                ('reasignada', models.BooleanField(default=False, null=True)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_inicio', models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Pagada'), ('8', 'Por pagar'), ('9', 'En espera')], max_length=2)),
                ('estado_fin', models.CharField(blank=True, choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Pagada'), ('8', 'Por pagar'), ('9', 'En espera')], max_length=2, null=True)),
                ('fecha_asignada', models.DateField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Incidencia')),
            ],
            options={
                'ordering': ['sprint', 'fecha_asignada'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.FloatField()),
                ('descripcion', models.CharField(max_length=1024)),
                ('horas_estimadas', models.FloatField()),
                ('horas_utilizadas', models.FloatField()),
                ('modificado', models.BooleanField(default=False)),
                ('pagado', models.BooleanField(default=False)),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Contratacion')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=512)),
                ('codigo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_revision', models.DateField()),
                ('numero', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Proyecto')),
            ],
            options={
                'ordering': ['numero', 'proyecto'],
            },
        ),
        migrations.AddField(
            model_name='planificacion',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Sprint'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Planificacion'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Producto'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sprint_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint_fin', to='tracking.Sprint'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sprint_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint_inicio', to='tracking.Sprint'),
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Factura'),
        ),
        migrations.AddField(
            model_name='contratacion',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Contratista'),
        ),
        migrations.AddField(
            model_name='contratacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Proyecto'),
        ),
        migrations.AddField(
            model_name='bitacora_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Producto'),
        ),
        migrations.AddField(
            model_name='bitacora_contratacion',
            name='contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Contratacion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Contratacion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Planificacion'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('numero', 'proyecto')},
        ),
    ]
