# Generated by Django 2.1.7 on 2019-03-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='estado_fin',
            field=models.CharField(blank=True, choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Cancelada')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='estado_inicio',
            field=models.CharField(blank=True, choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Cancelada')], max_length=2, null=True),
        ),
    ]
