# Generated by Django 2.1.7 on 2019-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='sprint',
            field=models.ManyToManyField(to='tracking.Sprint'),
        ),
    ]
