# Generated by Django 2.1.7 on 2019-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartel',
            name='numero',
            field=models.FloatField(),
        ),
    ]
