# Generated by Django 2.1.7 on 2019-02-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20190220_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='sprint_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sprint_fin', to='tracking.Sprint'),
        ),
    ]
