# Generated by Django 2.1.7 on 2019-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20190321_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='pago',
            field=models.CharField(choices=[('1', 'Pagada'), ('2', 'Por pagar'), ('3', 'Sin completar'), ('4', 'Desarrollo CI'), ('5', 'Errores')], default='3', max_length=2),
        ),
    ]
