# Generated by Django 2.2.10 on 2020-03-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200324_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratacion',
            options={'ordering': ('proyecto__codigo', 'contrato', 'tipo'), 'verbose_name': 'Contratación', 'verbose_name_plural': 'Contrataciones'},
        ),
    ]
