# Generated by Django 2.1.7 on 2019-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20190227_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='pago',
            field=models.CharField(choices=[('1', 'Pagada'), ('2', 'Por pagar'), ('3', 'Sin completar'), ('4', 'Desarrollo CI')], default='3', max_length=2),
        ),
    ]
