# Generated by Django 2.2.10 on 2020-03-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20200327_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitacoracontratacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='reasignada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
