# Generated by Django 2.1.7 on 2019-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190227_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'Cancelada')], max_length=2),
        ),
    ]
