# Generated by Django 2.2.10 on 2020-03-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200330_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='fecha_asignada',
            field=models.DateField(),
        ),
    ]
