# Generated by Django 2.1.7 on 2019-02-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20190227_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartel',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['sprint', 'fecha']},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['numero', 'proyecto']},
        ),
    ]
