# Generated by Django 2.2.10 on 2020-03-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20200330_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='clasificacion',
            field=models.CharField(choices=[('1', 'Sin pagar'), ('2', 'Por pagar'), ('3', 'Pagada'), ('4', 'Desarrollo CI'), ('5', 'Garantía')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho')], max_length=2),
        ),
    ]
