# Generated by Django 2.2.10 on 2020-03-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20200330_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='facturacion',
        ),
    ]
