# Generated by Django 2.2.10 on 2020-03-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_remove_planificacion_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='estado_fin',
            field=models.CharField(blank=True, choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'En espera')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='estado_inicio',
            field=models.CharField(choices=[('1', 'Por hacer'), ('2', 'En proceso'), ('3', 'Desarrollado'), ('4', 'En pruebas'), ('5', 'Aprobado por PO'), ('6', 'Hecho'), ('7', 'En espera')], max_length=2),
        ),
    ]
