# Generated by Django 2.2.10 on 2020-03-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200330_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='pago_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
