# Generated by Django 2.2.10 on 2020-04-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_contratacion_fecha_prorroga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratacion',
            options={'ordering': ('proyecto__codigo', 'contratista'), 'verbose_name': 'Contratación', 'verbose_name_plural': 'Contrataciones'},
        ),
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together={('sprint', 'incidencia', 'contratacion')},
        ),
    ]
