# Generated by Django 2.2.10 on 2020-04-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_incidencia_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ('producto__contratacion', 'numero'), 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together={('sprint', 'contratacion', 'incidencia')},
        ),
    ]
