# Generated by Django 2.2.10 on 2020-04-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20200403_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['sprint', 'incidencia', 'contratacion'], 'verbose_name': 'Planificación', 'verbose_name_plural': 'Planificaciones'},
        ),
    ]
